// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTOw7cC3517hVP2HkMZc9LCrhbhjC5Ko8',
    appId: '1:841917844306:web:64022af0b570210b85488b',
    messagingSenderId: '841917844306',
    projectId: 'research-hub-d9034',
    authDomain: 'research-hub-d9034.firebaseapp.com',
    storageBucket: 'research-hub-d9034.firebasestorage.app',
    measurementId: 'G-M10EZ1J6LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK0SMXmx5k1QSLDzQAYkltsKBjTf7s83M',
    appId: '1:841917844306:android:d6656144a2c6261f85488b',
    messagingSenderId: '841917844306',
    projectId: 'research-hub-d9034',
    storageBucket: 'research-hub-d9034.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfWRfGPR_gImj4PIKBkxBzKX1CZ4AFTdU',
    appId: '1:841917844306:ios:53be154834a0ba1485488b',
    messagingSenderId: '841917844306',
    projectId: 'research-hub-d9034',
    storageBucket: 'research-hub-d9034.firebasestorage.app',
    androidClientId: '841917844306-bk29nj4jp09komfdtfesbvribgjrcsqr.apps.googleusercontent.com',
    iosClientId: '841917844306-hu55ojbir872sdbsvnhdfn9j0k2di20c.apps.googleusercontent.com',
    iosBundleId: 'com.example.researchV07',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfWRfGPR_gImj4PIKBkxBzKX1CZ4AFTdU',
    appId: '1:841917844306:ios:53be154834a0ba1485488b',
    messagingSenderId: '841917844306',
    projectId: 'research-hub-d9034',
    storageBucket: 'research-hub-d9034.firebasestorage.app',
    androidClientId: '841917844306-bk29nj4jp09komfdtfesbvribgjrcsqr.apps.googleusercontent.com',
    iosClientId: '841917844306-hu55ojbir872sdbsvnhdfn9j0k2di20c.apps.googleusercontent.com',
    iosBundleId: 'com.example.researchV07',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTOw7cC3517hVP2HkMZc9LCrhbhjC5Ko8',
    appId: '1:841917844306:web:fbf2334fdb68fb2d85488b',
    messagingSenderId: '841917844306',
    projectId: 'research-hub-d9034',
    authDomain: 'research-hub-d9034.firebaseapp.com',
    storageBucket: 'research-hub-d9034.firebasestorage.app',
    measurementId: 'G-4B1HFE0VL5',
  );

}